#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2025-10-13 19:03:10
# @Author  : Hisham Haydar (Hisham.Haydar@liser.lu)
# @Link    : https://hisham-haydar.github.io/
# @Version : 1.0.0
#%% 
"""
Scenario builder for synthetic working-hour adjustments on single households by gender.

This script loads the filtered single datasets generated by `data_prep.py`,
creates counterfactual scenarios where heads work 0, 20, or 40 weekly hours,
recomputes head employment income accordingly, runs EUROMOD for each scenario,
merges the simulation outputs while preserving synthetic columns, and finally
adds an `other_members_income` field that aggregates post-simulation disposable
income (`ils_dispy`) for non-head members within each household.

Outputs are written to `Data/processed/scenarios`.
"""

from __future__ import annotations

import argparse
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
import euromod as em

from scratch.my_functions import sum_nonhead_income

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "Data"
PROCESSED_DIR = DATA_DIR / "processed"
SCENARIO_DIR = PROCESSED_DIR / "scenarios"
SCENARIO_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR = PROJECT_ROOT / "EUROMOD_RELEASES_J1.0+" / "EUROMOD_RELEASES_J1.0+"

# Configuration shared with preprocessing
TARGET_COUNTRY = "DE"
TARGET_SYSTEM = "DE_2014"
TARGET_DATASET = "DE_2015_a1"
SCENARIO_HOURS = (0, 20, 40)
WEEKS_PER_MONTH = 52 / 12  # Align with data_prep wage reconstruction
GENDERS: Sequence[str] = ("male", "female")
MONTHS_WORKED_COLUMNS = ("liwmy", "liwftmy", "liwptmy")
UNEMPLOYMENT_PREFIXES = ("bun",)
LES_NLF = 7  # Inactive / not in the labour force

LOGGER = logging.getLogger(__name__)

#%%
@dataclass
class EuromodContext:
    system: em.System  # type: ignore[name-defined]
    dataset_name: str



def _scenario_output_path(gender: str, hours: int) -> Path:
    return SCENARIO_DIR / f"single_{gender}_lhw_{hours}.parquet"

def _resolve_single_gender_dataset(gender_label: str) -> Path:
    if gender_label not in {"male", "female"}:
        raise ValueError("gender_label must be 'male' or 'female'.")
    base_name = f"singles_final_filtered_{gender_label}"
    candidates = [
        PROCESSED_DIR / f"{base_name}.parquet",
        PROCESSED_DIR / f"{base_name}.feather",
        PROCESSED_DIR / f"{base_name}.pkl",
        PROCESSED_DIR / f"{base_name}.pickle",
        PROCESSED_DIR / f"{base_name}.csv",
        PROCESSED_DIR / f"{base_name}.txt",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"Could not locate the filtered single {gender_label} dataset. "
        "Ensure `data_prep.py` has been executed and produced "
        f"`Data/processed/singles_final_filtered_{gender_label}.(parquet|pkl|csv|txt)`."
    )


def _read_dataframe(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".parquet":
        return pd.read_parquet(path)  # type: ignore[arg-type]
    if suffix == ".feather":
        return pd.read_feather(path)  # type: ignore[arg-type]
    if suffix in {".pkl", ".pickle"}:
        return pd.read_pickle(path)
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix == ".txt":
        return pd.read_csv(path, sep="\t")
    raise ValueError(f"Unsupported dataset format: {path}")


def _prepare_euromod() -> EuromodContext:
    model = em.Model(str(MODEL_DIR))
    country = model[TARGET_COUNTRY]
    try:
        system = country[TARGET_SYSTEM]
    except KeyError:
        system = next(iter(country.values()))  # fallback

    dataset = None
    if hasattr(system, "datasets"):
        try:
            dataset = system.datasets[TARGET_DATASET]  # type: ignore[index, attr-defined]
        except (KeyError, TypeError):
            dataset = None
    if dataset is None:
        candidates = [
            ds
            for ds in getattr(system, "bestmatch_datasets", [])
            if getattr(ds, "name", "") == TARGET_DATASET
        ]
        dataset = candidates[0] if candidates else system.bestmatch_datasets[0]

    dataset_name = getattr(dataset, "name", TARGET_DATASET)
    return EuromodContext(system=system, dataset_name=dataset_name)


def _create_scenario(df: pd.DataFrame, hours: int, les_nlf_code: int) -> pd.DataFrame:
    scenario = df.copy()
    if 'hh_IsHead' not in scenario.columns:
        raise KeyError("Column 'hh_IsHead' missing from dataset - cannot identify heads.")
    if 'yivwg' not in scenario.columns:
        raise KeyError("Column 'yivwg' missing from dataset - wage is required.")
    if 'yem' not in scenario.columns or 'lhw' not in scenario.columns:
        raise KeyError("Columns 'yem' and 'lhw' are required for scenario construction.")

    head_mask = scenario['hh_IsHead'] == 1
    non_head_mask = ~head_mask
    non_head_lhw = scenario.loc[non_head_mask, 'lhw'].copy()

    if 'lhw_original' not in scenario.columns:
        scenario['lhw_original'] = scenario['lhw']
    if 'yem_original' not in scenario.columns:
        scenario['yem_original'] = scenario['yem']
    if 'les' in scenario.columns and 'les_original' not in scenario.columns:
        scenario['les_original'] = scenario['les']

    scenario.loc[head_mask, 'lhw'] = hours
    scenario.loc[head_mask, 'yem'] = scenario.loc[head_mask, 'yivwg'] * hours * WEEKS_PER_MONTH

    if hours == 0:
        scenario.loc[head_mask, 'yem'] = 0
        if 'les' in scenario.columns:
            scenario.loc[head_mask, 'les'] = les_nlf_code
        for col in MONTHS_WORKED_COLUMNS:
            if col in scenario.columns:
                scenario.loc[head_mask, col] = 0
        for col in scenario.columns:
            if col.startswith('liw') and col.endswith('my'):
                scenario.loc[head_mask, col] = 0

    scenario['scenario_label'] = f'lhw_{hours}'
    scenario['scenario_hours'] = np.where(head_mask, hours, scenario['lhw'])
    scenario['yem_synthetic'] = np.where(head_mask, scenario['yem'], scenario['yem_original'])

    if not scenario.loc[non_head_mask, 'lhw'].equals(non_head_lhw):
        raise AssertionError('Non-head labour hours were modified during scenario construction.')

    return scenario



def _run_euromod(context: EuromodContext, df: pd.DataFrame) -> pd.DataFrame:
    sim = context.system.run(df, context.dataset_name)
    sim_df = sim.outputs[0]
    if not isinstance(sim_df, pd.DataFrame):
        sim_df = sim_df.to_dataframe()  # type: ignore[attr-defined]
    return sim_df


def _merge_simulation(
    scenario_df: pd.DataFrame,
    sim_df: pd.DataFrame,
    hours: int | None,
) -> pd.DataFrame:
    if 'idperson' not in scenario_df.columns or 'idperson' not in sim_df.columns:
        raise KeyError("Both scenario and simulation data must include 'idperson'.")

    rename_map = {
        col: f"{col}_sim"
        for col in sim_df.columns
        if col in scenario_df.columns and col != 'idperson'
    }
    sim_renamed = sim_df.rename(columns=rename_map)
    merged = scenario_df.merge(sim_renamed, on='idperson', how='left', validate='one_to_one')

    income_col = None
    if 'ils_dispy_sim' in merged.columns:
        income_col = 'ils_dispy_sim'
    elif 'ils_dispy' in merged.columns:
        income_col = 'ils_dispy'

    head_mask = merged['hh_IsHead'] == 1

    if income_col is None:
        merged['other_members_income'] = 0.0
        merged['consumption'] = np.where(head_mask, 0.0, 0.0)
        return merged

    if 'idhh' not in merged.columns:
        raise KeyError("Merged dataset must include 'idhh'.")

    head_counts = (
        pd.to_numeric(merged['hh_IsHead'], errors='coerce')
        .fillna(0)
        .groupby(merged['idhh'])
        .sum(min_count=1)
    )
    multi_head_households = head_counts[head_counts != 1]
    if not multi_head_households.empty:
        raise AssertionError(
            "Each household must have exactly one head to compute consumption. "
            f"Problematic household ids: {tuple(multi_head_households.index)}"
        )

    income = merged[income_col].fillna(0.0)
    household_income = (
        merged.groupby('idhh')[income_col]
        .transform('sum')
        .fillna(0.0)
    )

    merged['other_members_income'] = np.where(
        head_mask,
        household_income - income,
        0.0,
    )
    merged['consumption'] = np.where(
        head_mask,
        household_income,
        0.0,
    )

    expected_other_income = (
        merged['idhh']
        .map(sum_nonhead_income(merged, income_col))
        .fillna(0.0)
    )
    if not np.allclose(
        merged.loc[head_mask, 'other_members_income'],
        expected_other_income.loc[head_mask],
        atol=1e-6,
    ):
        raise AssertionError(
            "Computed other_members_income does not match summed non-head income."
        )

    household_consumption = (
        merged.groupby('idhh')['consumption']
        .transform('sum')
        .fillna(0.0)
    )
    if not np.allclose(household_consumption, household_income, atol=1e-6):
        raise AssertionError(
            "Household consumption totals must match disposable income sums."
        )

    if hours == 0:
        zero_cols = [
            col
            for col in merged.columns
            if col.endswith('_sim')
            and any(col.lower().startswith(prefix) for prefix in UNEMPLOYMENT_PREFIXES)
        ]
        if zero_cols:
            merged.loc[head_mask, zero_cols] = 0.0
            if not (merged.loc[head_mask, zero_cols] == 0).all().all():
                raise AssertionError('Unemployment components not fully cleared for 0h scenario.')

    return merged


def _save_scenario(df: pd.DataFrame, gender: str, hours: int) -> Path:
    path = _scenario_output_path(gender, hours)
    df.to_parquet(path, engine="pyarrow", compression="snappy")  # type: ignore[arg-type]
    return path


def run_all_scenarios(
    hours_list: Iterable[int] = SCENARIO_HOURS,
    genders: Iterable[str] = GENDERS,
    context: EuromodContext | None = None,
) -> dict[str, dict[int, dict[str, object]]]:
    if context is None:
        context = _prepare_euromod()

    hours_seq = tuple(hours_list)
    results: dict[str, dict[int, dict[str, object]]] = {}
    for gender in genders:
        dataset_path = _resolve_single_gender_dataset(gender)
        base_df = _read_dataframe(dataset_path)

        gender_results: dict[int, dict[str, object]] = {}
        for hours in hours_seq:
            scenario_df = _create_scenario(base_df, hours, LES_NLF)
            sim_df = _run_euromod(context, scenario_df)
            merged_df = _merge_simulation(scenario_df, sim_df, hours)
            output_path = _save_scenario(merged_df, gender, hours)
            gender_results[hours] = {
                'input_rows': len(scenario_df),
                'output_rows': len(merged_df),
                'output_path': output_path,
            }
            LOGGER.info("[%s] Scenario %sh - rows: %s, saved to %s", gender, hours, f"{len(merged_df):,}", output_path)
        results[gender] = gender_results
    return results



def run_baseline_and_build_wide(
    gender: str = 'male',
    hours_list: Iterable[int] = SCENARIO_HOURS,
    context: EuromodContext | None = None,
    ensure_scenarios: bool = True,
) -> dict[str, object]:
    hours_seq = tuple(hours_list)
    if context is None:
        context = _prepare_euromod()

    if ensure_scenarios:
        missing = [h for h in hours_seq if not _scenario_output_path(gender, h).exists()]
        if missing:
            LOGGER.info("Missing scenario files for %s at hours %s; generating.", gender, missing)
            run_all_scenarios(hours_seq, (gender,), context)

    dataset_path = _resolve_single_gender_dataset(gender)
    base_df = _read_dataframe(dataset_path)

    baseline_sim = _run_euromod(context, base_df)
    baseline_merged = _merge_simulation(base_df.copy(), baseline_sim, hours=None)

    head_mask = baseline_merged['hh_IsHead'] == 1
    baseline_heads = baseline_merged.loc[head_mask].copy()

    if 'lhw_original' not in baseline_heads.columns:
        baseline_heads['lhw_original'] = baseline_heads['lhw']
    if 'consumption' not in baseline_heads.columns:
        raise KeyError("Baseline merge must produce 'consumption'.")
    baseline_heads['consumption_original'] = baseline_heads['consumption']
    baseline_heads['dag2'] = baseline_heads['dag'] ** 2

    if 'num_children_total' in baseline_heads.columns:
        baseline_heads['num_children_total'] = baseline_heads['num_children_total'].fillna(0).astype(int)
    else:
        child_counts = (baseline_merged['dag'] < 16).groupby(baseline_merged['idhh']).sum(min_count=1)
        baseline_heads['num_children_total'] = baseline_heads['idhh'].map(child_counts).fillna(0).astype(int)

    if 'deh' in baseline_heads.columns:
        education_dummies = pd.get_dummies(baseline_heads['deh'], prefix='deh', dtype=int)
    else:
        education_dummies = pd.DataFrame(index=baseline_heads.index)

    wide = baseline_heads[['idhh', 'idperson', 'dag', 'dag2', 'num_children_total', 'lhw_original', 'consumption_original']].copy()
    if not education_dummies.empty:
        wide = pd.concat([wide, education_dummies], axis=1)

    for hours in hours_seq:
        scenario_path = _scenario_output_path(gender, hours)
        scenario_df = _read_dataframe(scenario_path)
        scenario_heads = scenario_df.loc[scenario_df['hh_IsHead'] == 1, ['idhh', 'lhw', 'consumption']].copy()
        scenario_heads = scenario_heads.rename(columns={'lhw': f'lhw_{hours}', 'consumption': f'consumption_{hours}'})
        wide = wide.merge(scenario_heads, on='idhh', how='left')

    wide = wide.sort_values('idhh').reset_index(drop=True)

    priority_order = {20: 0, 40: 1, 0: 2}

    def _select_actual(value: float) -> int:
        return min(hours_seq, key=lambda h: (abs(value - h), priority_order.get(h, len(priority_order))))

    wide['actual_choice'] = wide['lhw_original'].apply(_select_actual)

    for hours in hours_seq:
        wide[f'is_actual_{hours}'] = (wide['actual_choice'] == hours).astype(int)

    dummy_cols = [f'is_actual_{hours}' for hours in hours_seq]
    if not (wide[dummy_cols].sum(axis=1) == 1).all():
        raise AssertionError('Actual choice indicators must sum to 1 for each head.')

    parquet_path = SCENARIO_DIR / f'heads_wide_single_{gender}.parquet'
    csv_path = SCENARIO_DIR / f'heads_wide_single_{gender}.csv'
    wide.to_parquet(parquet_path, engine='pyarrow', compression='snappy')
    wide.to_csv(csv_path, index=False)

    LOGGER.info('Wide dataset for %s saved to %s and %s', gender, parquet_path, csv_path)
    return {
        'gender': gender,
        'rows': len(wide),
        'parquet_path': parquet_path,
        'csv_path': csv_path,
    }

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description='Build working-hour scenarios for single households.')
    parser.add_argument('--hours', nargs='+', type=int, default=list(SCENARIO_HOURS), help='Scenario hours to evaluate.')
    parser.add_argument('--scenarios', nargs='+', choices=GENDERS, help='Run scenarios for the specified genders.')
    parser.add_argument('--wide', nargs='+', choices=GENDERS, help='Build wide DCM input for the specified genders.')
    parser.add_argument('--all', nargs='+', choices=GENDERS, help='Run scenarios and build wide datasets for the specified genders.')
    args, unknown = parser.parse_known_args(argv)
    if unknown:
        LOGGER.warning("Ignoring unknown CLI arguments: %s", unknown)

    logging.basicConfig(level=logging.INFO, format='%(message)s')

    hours_seq = tuple(args.hours)
    context: EuromodContext | None = None

    if args.all:
        context = _prepare_euromod()
        run_all_scenarios(hours_seq, args.all, context)
        for gender in args.all:
            run_baseline_and_build_wide(gender, hours_seq, context=context, ensure_scenarios=False)
        return

    performed = False

    if args.scenarios:
        context = context or _prepare_euromod()
        run_all_scenarios(hours_seq, args.scenarios, context)
        performed = True

    if args.wide:
        context = context or _prepare_euromod()
        for gender in args.wide:
            run_baseline_and_build_wide(gender, hours_seq, context=context, ensure_scenarios=True)
        performed = True

    if not performed:
        run_all_scenarios(hours_seq, GENDERS, context)
if __name__ == "__main__":
    main()
#%% 
import pandas as pd
df_m_20 = pd.read_parquet(Path("Data/processed/scenarios/single_male_lhw_20.parquet"))
df_m_20.head()

#%% 

df_m_0 = pd.read_parquet(Path("Data/processed/scenarios/single_male_lhw_0.parquet"))
df_m_0.head()
#%% 

# %%
