#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2025-10-13 19:03:10
# @Author  : Hisham Haydar (Hisham.Haydar@liser.lu)
# @Link    : https://hisham-haydar.github.io/
# @Version : 1.0.0
#%% 
"""
Scenario builder for synthetic working-hour adjustments on single households by gender.

This script loads the filtered single datasets generated by `data_prep.py`,
creates seven bucketed counterfactual scenarios (h0–h6) where head labour
hours are either held at their observed value (original bucket) or redrawn
from a beta distribution restricted to the relevant interval, re-runs
EUROMOD for each scenario, merges the simulation outputs while preserving
synthetic columns, and finally adds an `other_members_income` field that
aggregates post-simulation disposable income (`ils_dispy`) for non-head
members within each household.

Outputs are written to `Data/processed/scenarios`.
"""

from __future__ import annotations

import argparse
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
import euromod as em

from scratch.my_functions import sum_nonhead_income

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "Data"
PROCESSED_DIR = DATA_DIR / "processed"
SCENARIO_DIR = PROCESSED_DIR / "scenarios"
SCENARIO_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR = PROJECT_ROOT / "EUROMOD_RELEASES_J1.0+" / "EUROMOD_RELEASES_J1.0+"

# Configuration shared with preprocessing
TARGET_COUNTRY = "DE"
TARGET_SYSTEM = "DE_2014"
TARGET_DATASET = "DE_2015_a1"
WEEKS_PER_MONTH = 52 / 12  # Align with data_prep wage reconstruction
GENDERS: Sequence[str] = ("male", "female")
MONTHS_WORKED_COLUMNS = ("liwmy", "liwftmy", "liwptmy")
UNEMPLOYMENT_PREFIXES = ("bun",)
LES_NLF = 7  # Inactive / not in the labour force

# Scenario configuration: seven hour buckets with Beta-drawn counterfactuals.
SCENARIO_BUCKETS: Sequence[tuple[str, int, int]] = (
    ("h0", 0, 0),
    ("h1", 1, 10),
    ("h2", 11, 20),
    ("h3", 21, 30),
    ("h4", 31, 40),
    ("h5", 41, 50),
    ("h6", 51, 60),
)
SCENARIO_LABELS: Sequence[str] = tuple(label for label, _, _ in SCENARIO_BUCKETS)
SCENARIO_RANGE_LOOKUP: dict[str, tuple[int, int]] = {
    label: (lower, upper) for label, lower, upper in SCENARIO_BUCKETS
}
BETA_ALPHA = 2.0
BETA_BETA = 2.0
RNG_SEED = 42  # Deterministic draws for reproducibility across runs

LOGGER = logging.getLogger(__name__)

#%%
@dataclass
class EuromodContext:
    system: em.System  # type: ignore[name-defined]
    dataset_name: str



def _scenario_output_path(gender: str, label: str) -> Path:
    """Return the canonical parquet path for a gender/label scenario."""
    return SCENARIO_DIR / f"single_{gender}_{label}.parquet"

def _resolve_single_gender_dataset(gender_label: str) -> Path:
    """Locate the processed singles dataset for the requested gender."""
    if gender_label not in {"male", "female"}:
        raise ValueError("gender_label must be 'male' or 'female'.")
    base_name = f"singles_final_filtered_{gender_label}"
    candidates = [
        PROCESSED_DIR / f"{base_name}.parquet",
        PROCESSED_DIR / f"{base_name}.feather",
        PROCESSED_DIR / f"{base_name}.pkl",
        PROCESSED_DIR / f"{base_name}.pickle",
        PROCESSED_DIR / f"{base_name}.csv",
        PROCESSED_DIR / f"{base_name}.txt",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"Could not locate the filtered single {gender_label} dataset. "
        "Ensure `data_prep.py` has been executed and produced "
        f"`Data/processed/singles_final_filtered_{gender_label}.(parquet|pkl|csv|txt)`."
    )


def _read_dataframe(path: Path) -> pd.DataFrame:
    """Read a dataframe while handling multiple supported extensions."""
    suffix = path.suffix.lower()
    if suffix == ".parquet":
        return pd.read_parquet(path)  # type: ignore[arg-type]
    if suffix == ".feather":
        return pd.read_feather(path)  # type: ignore[arg-type]
    if suffix in {".pkl", ".pickle"}:
        return pd.read_pickle(path)
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix == ".txt":
        return pd.read_csv(path, sep="\t")
    raise ValueError(f"Unsupported dataset format: {path}")


def _prepare_euromod() -> EuromodContext:
    """Initialise EUROMOD connectors and resolve dataset metadata."""
    model = em.Model(str(MODEL_DIR))
    country = model[TARGET_COUNTRY]
    try:
        system = country[TARGET_SYSTEM]
    except KeyError:
        system = next(iter(country.values()))  # fallback

    dataset = None
    if hasattr(system, "datasets"):
        try:
            dataset = system.datasets[TARGET_DATASET]  # type: ignore[index, attr-defined]
        except (KeyError, TypeError):
            dataset = None
    if dataset is None:
        candidates = [
            ds
            for ds in getattr(system, "bestmatch_datasets", [])
            if getattr(ds, "name", "") == TARGET_DATASET
        ]
        dataset = candidates[0] if candidates else system.bestmatch_datasets[0]

    dataset_name = getattr(dataset, "name", TARGET_DATASET)
    return EuromodContext(system=system, dataset_name=dataset_name)


def _assign_hour_bucket(hours: pd.Series) -> pd.Series:
    """Map observed head hours to their scenario label."""
    bucket_labels = pd.Series(index=hours.index, dtype="object")
    remaining = hours.copy()
    for label, lower, upper in SCENARIO_BUCKETS:
        mask = remaining.between(lower, upper, inclusive="both")
        bucket_labels.loc[mask] = label
        remaining.loc[mask] = np.nan
    if bucket_labels.isna().any():
        bad = hours.loc[bucket_labels.isna()].unique()
        raise ValueError(
            "Encountered head working hours outside configured buckets: "
            f"{', '.join(str(x) for x in sorted(bad))}."
            " Consider adjusting SCENARIO_BUCKETS."
        )
    return bucket_labels


def _sample_bucket_hours(
    size: int,
    lower: int,
    upper: int,
    rng: np.random.Generator,
    alpha: float,
    beta: float,
) -> np.ndarray:
    """Draw counterfactual hours within [lower, upper] using a Beta distribution."""
    if size == 0:
        return np.array([], dtype=float)
    if lower == upper:
        return np.full(size, float(lower))
    draws = rng.beta(alpha, beta, size=size)
    sampled = lower + draws * (upper - lower)
    sampled = np.ceil(sampled)  # Align with integer hour bins
    return np.clip(sampled, lower, upper)


def _generate_head_hour_targets(
    heads_df: pd.DataFrame,
    labels: Sequence[str],
    rng: np.random.Generator,
    alpha: float,
    beta: float,
) -> tuple[pd.Series, dict[str, pd.Series]]:
    """Create per-scenario hour assignments for each household head."""
    hours = pd.to_numeric(heads_df["lhw"], errors="coerce")
    if hours.isna().any():
        raise ValueError("Head labour hours contain missing values; cannot assign buckets.")
    hours.index = heads_df["idperson"]

    original_labels = _assign_hour_bucket(hours)

    targets: dict[str, pd.Series] = {}
    requested = set(labels)
    for label, (lower, upper) in SCENARIO_RANGE_LOOKUP.items():
        if label not in requested:
            continue
        target = pd.Series(np.nan, index=hours.index, dtype=float)
        mask_original = original_labels == label
        target.loc[mask_original] = hours.loc[mask_original]

        mask_counterfactual = ~mask_original
        sample_size = int(mask_counterfactual.sum())
        if sample_size > 0:
            sampled = _sample_bucket_hours(sample_size, lower, upper, rng, alpha, beta)
            target.loc[mask_counterfactual] = sampled
        else:
            target.loc[mask_counterfactual] = float(lower if lower == upper else upper)
        targets[label] = target

    return original_labels, targets


def _create_scenario(
    df: pd.DataFrame,
    head_hours: pd.Series,
    label: str,
    les_nlf_code: int,
) -> pd.DataFrame:
    """Adjust head working hours/income while preserving non-head records."""
    scenario = df.copy()
    if 'hh_IsHead' not in scenario.columns:
        raise KeyError("Column 'hh_IsHead' missing from dataset - cannot identify heads.")
    if 'yivwg' not in scenario.columns:
        raise KeyError("Column 'yivwg' missing from dataset - wage is required.")
    if 'yem' not in scenario.columns or 'lhw' not in scenario.columns:
        raise KeyError("Columns 'yem' and 'lhw' are required for scenario construction.")

    head_mask = scenario['hh_IsHead'] == 1
    non_head_mask = ~head_mask
    non_head_lhw = scenario.loc[non_head_mask, 'lhw'].copy()

    if 'lhw_original' not in scenario.columns:
        scenario['lhw_original'] = scenario['lhw']
    if 'yem_original' not in scenario.columns:
        scenario['yem_original'] = scenario['yem']
    if 'les' in scenario.columns and 'les_original' not in scenario.columns:
        scenario['les_original'] = scenario['les']

    head_ids = scenario.loc[head_mask, 'idperson']
    aligned_hours = head_hours.reindex(head_ids)
    if aligned_hours.isna().any():
        raise ValueError(f"Missing hour assignments for scenario '{label}'.")

    scenario.loc[head_mask, 'lhw'] = aligned_hours.values
    scenario.loc[head_mask, 'yem'] = scenario.loc[head_mask, 'yivwg'] * scenario.loc[head_mask, 'lhw'] * WEEKS_PER_MONTH

    zero_mask = head_mask & scenario['lhw'].eq(0)
    if zero_mask.any():
        scenario.loc[zero_mask, 'yem'] = 0
        if 'les' in scenario.columns:
            scenario.loc[zero_mask, 'les'] = les_nlf_code
        for col in MONTHS_WORKED_COLUMNS:
            if col in scenario.columns:
                scenario.loc[zero_mask, col] = 0
        for col in scenario.columns:
            if col.startswith('liw') and col.endswith('my'):
                scenario.loc[zero_mask, col] = 0

    scenario['scenario_label'] = label
    scenario['scenario_hours'] = scenario['lhw']
    scenario['yem_synthetic'] = np.where(head_mask, scenario['yem'], scenario['yem_original'])

    if not scenario.loc[non_head_mask, 'lhw'].equals(non_head_lhw):
        raise AssertionError('Non-head labour hours were modified during scenario construction.')

    return scenario



def _run_euromod(context: EuromodContext, df: pd.DataFrame) -> pd.DataFrame:
    """Run EUROMOD on a dataframe and return the first output table."""
    sim = context.system.run(df, context.dataset_name)
    sim_df = sim.outputs[0]
    if not isinstance(sim_df, pd.DataFrame):
        sim_df = sim_df.to_dataframe()  # type: ignore[attr-defined]
    return sim_df


def _merge_simulation(
    scenario_df: pd.DataFrame,
    sim_df: pd.DataFrame,
    scenario_label: str | None,
) -> pd.DataFrame:
    """Combine scenario inputs with simulation outputs and build head totals."""
    if 'idperson' not in scenario_df.columns or 'idperson' not in sim_df.columns:
        raise KeyError("Both scenario and simulation data must include 'idperson'.")

    # Rename simulated columns that clash with original names (except idperson).
    rename_map = {
        col: f"{col}_sim"
        for col in sim_df.columns
        if col in scenario_df.columns and col != 'idperson'
    }
    sim_renamed = sim_df.rename(columns=rename_map)
    # Merge simulated outputs back to the scenario rows on a one-to-one basis.
    merged = scenario_df.merge(sim_renamed, on='idperson', how='left', validate='one_to_one')

    income_col = None
    if 'ils_dispy_sim' in merged.columns:
        income_col = 'ils_dispy_sim'
    elif 'ils_dispy' in merged.columns:
        income_col = 'ils_dispy'

    head_mask = merged['hh_IsHead'] == 1

    if income_col is None:
        merged['other_members_income'] = 0.0
        merged['consumption'] = np.where(head_mask, 0.0, 0.0)
        return merged

    if 'idhh' not in merged.columns:
        raise KeyError("Merged dataset must include 'idhh'.")

    # Ensure each household retains exactly one head record.
    head_counts = (
        pd.to_numeric(merged['hh_IsHead'], errors='coerce')
        .fillna(0)
        .groupby(merged['idhh'])
        .sum(min_count=1)
    )
    multi_head_households = head_counts[head_counts != 1]
    if not multi_head_households.empty:
        raise AssertionError(
            "Each household must have exactly one head to compute consumption. "
            f"Problematic household ids: {tuple(multi_head_households.index)}"
        )

    income = merged[income_col].fillna(0.0)
    household_income = (
        merged.groupby('idhh')[income_col]
        .transform('sum')  # Broadcast household disposable income to all members.
        .fillna(0.0)
    )

    merged['other_members_income'] = np.where(
        head_mask,
        household_income - income,
        0.0,
    )
    merged['consumption'] = np.where(
        head_mask,
        household_income,
        0.0,
    )

    expected_other_income = (
        merged['idhh']
        .map(sum_nonhead_income(merged, income_col))
        .fillna(0.0)
    )
    if not np.allclose(
        merged.loc[head_mask, 'other_members_income'],
        expected_other_income.loc[head_mask],
        atol=1e-6,
    ):
        raise AssertionError(
            "Computed other_members_income does not match summed non-head income."
        )

    household_consumption = (
        merged.groupby('idhh')['consumption']
        .transform('sum')
        .fillna(0.0)
    )
    if not np.allclose(household_consumption, household_income, atol=1e-6):
        raise AssertionError(
            "Household consumption totals must match disposable income sums."
        )

    if scenario_label == "h0":
        # Clear unemployment-related simulated columns when heads are forced to 0 hours.
        zero_cols = [
            col
            for col in merged.columns
            if col.endswith('_sim')
            and any(col.lower().startswith(prefix) for prefix in UNEMPLOYMENT_PREFIXES)
        ]
        if zero_cols:
            merged.loc[head_mask, zero_cols] = 0.0
            if not (merged.loc[head_mask, zero_cols] == 0).all().all():
                raise AssertionError('Unemployment components not fully cleared for 0h scenario.')

    return merged


def _save_scenario(df: pd.DataFrame, gender: str, label: str) -> Path:
    path = _scenario_output_path(gender, label)
    df.to_parquet(path, engine="pyarrow", compression="snappy")  # type: ignore[arg-type]
    return path


def run_all_scenarios(
    scenario_labels: Iterable[str] = SCENARIO_LABELS,
    genders: Iterable[str] = GENDERS,
    context: EuromodContext | None = None,
    *,
    beta_alpha: float = BETA_ALPHA,
    beta_beta: float = BETA_BETA,
    rng_seed: int = RNG_SEED,
) -> dict[str, dict[str, object]]:
    """Generate, simulate, and persist all requested counterfactual scenarios."""
    if context is None:
        context = _prepare_euromod()

    label_seq = tuple(scenario_labels)
    results: dict[str, dict[str, object]] = {}
    for gender_idx, gender in enumerate(genders):
        dataset_path = _resolve_single_gender_dataset(gender)
        base_df = _read_dataframe(dataset_path)
        heads_df = base_df.loc[base_df["hh_IsHead"] == 1].copy()

        rng = np.random.default_rng(rng_seed + gender_idx)
        original_labels, hour_targets = _generate_head_hour_targets(
            heads_df,
            label_seq,
            rng,
            beta_alpha,
            beta_beta,
        )

        gender_results: dict[str, object] = {"original_labels": original_labels.to_dict()}
        scenario_outputs: dict[str, dict[str, object]] = {}
        for label in label_seq:
            head_hours = hour_targets[label]
            scenario_df = _create_scenario(base_df, head_hours, label, LES_NLF)
            sim_df = _run_euromod(context, scenario_df)
            merged_df = _merge_simulation(scenario_df, sim_df, label)
            output_path = _save_scenario(merged_df, gender, label)
            scenario_outputs[label] = {
                "input_rows": len(scenario_df),
                "output_rows": len(merged_df),
                "output_path": output_path,
            }
            LOGGER.info(
                "[%s] Scenario %s - rows: %s, saved to %s",
                gender,
                label,
                f"{len(merged_df):,}",
                output_path,
            )
        gender_results["scenarios"] = scenario_outputs

        wide_info = run_baseline_and_build_wide(
            gender=gender,
            scenario_labels=label_seq,
            context=context,
            ensure_scenarios=False,
        )
        gender_results["wide"] = wide_info
        LOGGER.info(
            "[%s] Wide dataset refreshed - rows: %s, saved to %s",
            gender,
            wide_info.get("rows", "n/a"),
            wide_info.get("parquet_path"),
        )

        results[gender] = gender_results
    return results



def run_baseline_and_build_wide(
    gender: str = "male",
    scenario_labels: Iterable[str] = SCENARIO_LABELS,
    context: EuromodContext | None = None,
    ensure_scenarios: bool = True,
) -> dict[str, object]:
    label_seq = tuple(scenario_labels)
    if context is None:
        context = _prepare_euromod()

    if ensure_scenarios:
        missing = [label for label in label_seq if not _scenario_output_path(gender, label).exists()]
        if missing:
            LOGGER.info("Missing scenario files for %s at %s; generating.", gender, missing)
            run_all_scenarios(label_seq, (gender,), context)

    dataset_path = _resolve_single_gender_dataset(gender)
    base_df = _read_dataframe(dataset_path)

    # Start from the original singles dataset restricted to one row per household head.
    base_heads = base_df.loc[base_df['hh_IsHead'] == 1].copy()
    if 'idhh' not in base_heads.columns:
        raise KeyError("Singles dataset must include 'idhh'.")
    if 'lhw' not in base_heads.columns:
        raise KeyError("Singles dataset must include 'lhw' for actual choice computation.")

    wide = base_heads.copy()

    for label in label_seq:
        scenario_path = _scenario_output_path(gender, label)
        scenario_df = _read_dataframe(scenario_path)

        if 'hh_IsHead' not in scenario_df.columns:
            raise KeyError("Scenario data must include 'hh_IsHead'.")
        scenario_heads = scenario_df.loc[scenario_df['hh_IsHead'] == 1].copy()

        required_cols = {'idhh', 'lhw', 'yem', 'consumption', 'other_members_income'}
        missing_required = required_cols - set(scenario_heads.columns)
        if missing_required:
            raise KeyError(f"Scenario file for {gender} at {label} missing required columns: {sorted(missing_required)}")

        income_col = None
        if 'ils_dispy_sim' in scenario_heads.columns:
            income_col = 'ils_dispy_sim'
        elif 'ils_dispy' in scenario_heads.columns:
            income_col = 'ils_dispy'
        else:
            raise KeyError("Scenario file must include 'ils_dispy_sim' or 'ils_dispy'.")

        # Keep only the head-level measures we want to copy to the wide table.
        selected_cols = ['idhh', 'lhw', 'yem', income_col, 'consumption', 'other_members_income']
        scenario_heads = scenario_heads[selected_cols]
        rename_map = {
            'lhw': f'lhw_{label}',
            'yem': f'yem_{label}',
            income_col: f'ils_dispy_{label}',
            'consumption': f'consumption_{label}',
            'other_members_income': f'other_members_income_{label}',
        }
        scenario_heads = scenario_heads.rename(columns=rename_map)

        # Merge scenario-specific fields onto the base head row.
        wide = wide.merge(scenario_heads, on='idhh', how='left', validate='one_to_one')

    wide = wide.sort_values('idhh').reset_index(drop=True)

    if 'lhw_original' in wide.columns:
        actual_hours = pd.to_numeric(wide['lhw_original'], errors='coerce')
    else:
        actual_hours = pd.to_numeric(wide['lhw'], errors='coerce')

    actual_hours.index = wide['idperson']
    actual_labels = _assign_hour_bucket(actual_hours)
    wide['actual_choice'] = actual_labels.reindex(wide['idperson']).values

    for label in label_seq:
        wide[f'is_actual_{label}'] = (wide['actual_choice'] == label).astype(int)

    dummy_cols = [f'is_actual_{label}' for label in label_seq]
    # Guard against multiple selections or missing assignment per household.
    if not (wide[dummy_cols].sum(axis=1) == 1).all():
        raise AssertionError('Actual choice indicators must sum to 1 for each head.')

    parquet_path = SCENARIO_DIR / f'heads_wide_single_{gender}.parquet'
    csv_path = SCENARIO_DIR / f'heads_wide_single_{gender}.csv'
    # Persist both parquet and CSV variants for downstream workflows.
    wide.to_parquet(parquet_path, engine='pyarrow', compression='snappy')
    wide.to_csv(csv_path, index=False)

    LOGGER.info('Wide dataset for %s saved to %s and %s', gender, parquet_path, csv_path)
    return {
        'gender': gender,
        'rows': len(wide),
        'parquet_path': parquet_path,
        'csv_path': csv_path,
    }

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description='Build working-hour scenarios for single households.')
    parser.add_argument(
        '--labels',
        nargs='+',
        choices=SCENARIO_LABELS,
        default=list(SCENARIO_LABELS),
        help='Scenario labels to evaluate (default: all buckets h0-h6).',
    )
    parser.add_argument('--scenarios', nargs='+', choices=GENDERS, help='Run scenarios for the specified genders.')
    parser.add_argument('--wide', nargs='+', choices=GENDERS, help='Build wide DCM input for the specified genders.')
    parser.add_argument('--all', nargs='+', choices=GENDERS, help='Run scenarios and build wide datasets for the specified genders.')
    args, unknown = parser.parse_known_args(argv)
    if unknown:
        LOGGER.warning("Ignoring unknown CLI arguments: %s", unknown)

    logging.basicConfig(level=logging.INFO, format='%(message)s')

    selected_labels = tuple(args.labels)
    context: EuromodContext | None = None

    if args.all:
        context = _prepare_euromod()
        run_all_scenarios(selected_labels, args.all, context)
        return

    performed = False

    if args.scenarios:
        context = context or _prepare_euromod()
        run_all_scenarios(selected_labels, args.scenarios, context)
        performed = True

    if args.wide:
        context = context or _prepare_euromod()
        for gender in args.wide:
            run_baseline_and_build_wide(gender, selected_labels, context=context, ensure_scenarios=True)
        performed = True

    if not performed:
        run_all_scenarios(selected_labels, GENDERS, context)
if __name__ == "__main__":
    main()
#%% 
# The remaining cells are ad-hoc exploratory checks kept for interactive use.
import pandas as pd
df_m_h3 = pd.read_parquet(Path("Data/processed/scenarios/single_male_h3.parquet"))
df_m_h3.head()

#%% 

df_m_h0 = pd.read_parquet(Path("Data/processed/scenarios/single_male_h0.parquet"))
df_m_h0.head()
#%% 
df_m= pd.read_parquet(Path("Data/processed/singles_final_filtered_male.parquet"))
df_m.head()

# %%
# Load the DataFrames
df_wide_m = pd.read_parquet(
    Path("Data/processed/scenarios/heads_wide_single_male.parquet"))
df_wide_m.head()
#%% 
